### PR TITLE
Data type operator support fixes

### PR DESCRIPTION
**Pull request by mkruk-u2**
Data type supports NEQ operator, but doesn't support IN operator

### CODE REVIEW

**Comment by yakobe** [comment]
Is there a way to test this?

**Comment by mkruk-u2** [comment]
Yes, we could create a test for interpreter class.

For data type classes the test would just check if `getAvailableFilterMethods` method returns expected array, so probably doesn't make sense to test this.

**Comment by yakobe** [comment]
makes sense to me. it enforces that it has the ones that we expect doesn't it? in case someone removes ore changes it? we dont nee to test the whole class from scratch, but when a bug happens it shows that we forgot something. a test tries to make sure it doesn't happen again.

**Comment by mkruk-u2** [comment]
```
getAvailableMethods()
{
    return ["this", "that"];
}

testThis()
{
    $this->assertSame(
        ["this", "that"],
        $dataType->getAvailableMethods()
    );
}
```

Do you really see a point in testing this like that?
Or you're thinking about something different?

**Comment by yakobe** [comment]
it like a spec. "the DateDataType should have the folloing filter methods"

i mean, technically you shouldn't touch the code until the tests go red...
>  TDD is lovely 👍

**Comment by yakobe** [comment]
didn't mean to close it 😸

**Comment by yakobe** [comment]
Went above and beyond on the old tests ther 😄 

I would say :shipit:

**Pull request merged**
