### PR TITLE
Removed IS_NULL filtering method

### PR DESCRIPTION
**Pull request by mkruk-u2**

### CODE REVIEW

**Comment by yakobe** [comment]
Could this cause any BC breaks for us?

**Comment by mkruk-u2** [comment]
Well, if someone is using removed constant, then yes, it could.

**Comment by yakobe** [comment]
As long as we don't 😝

**Comment by mkruk-u2** [comment]
We might have some constants left in code (not code constant, but string constants, e.g. "IS_NULL"), but they're not used to implement working functionality. I'll verify tomorrow if we need to change something in our code.

**Comment by mkruk-u2** [comment]
It seems there are no leftovers from this IS_NULL thingy in our code.

**Pull request merged**
